name: crypto_tracker
description: "A VIP Crypto Tracker App with premium animations and design"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  fl_chart: ^0.66.2  # Add this line here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets later, uncomment below:
  # assets:
  #   - assets/images/
  
  # Remove fonts section if you don't have the font files
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Inter-ExtraBold.ttf
  #         weight: 800